### ISSUE TITLE
Поправить pandas метод

### ISSUE THREAD

**Issue by gazon1** [antklen/short-texts-clustering#1]
Привет!
В стримлите ошибка, "dataframe has no tolist method". [Здесь](https://github.com/antklen/short-texts-clustering/blob/a833b7dae826f859f16afa1a530179da65913d71/app/data.py#L40) нужно написать `phrases.values.tolist()`

**Comment by antklen** [comment]
Привет! Спасибо, действительно был баг. Исправил, только немного в [другом месте](https://github.com/antklen/short-texts-clustering/blob/master/app/data.py#L30).
